machine:
  pre:
    - mkdir ~/.yarn-cache
  node:
    version: v4.6.1

dependencies:
  override:
    - ./scripts/misc/installPackageManager && yarn install
  cache_directories:
    - ~/.yarn-cache

test:
  override:
    - yarn test

deployment:
  prod:
    branch: master
    heroku:
      appname: gatsby-auto-deploy
